@startuml
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

package application{
            class Application{
                    - Game game
                    - Application(GameCreator gameCreat)
                    - void runApplication()
                     + static void main(String[] args)
                            }
            abstract class ArgumentParser{}

            class DataCollector{}
}

package character{
                class Character {}
                class Human {}

                class Infected {}
                class Personage {}
}

package displayer {
                class BoardDisplayer {}
                class PersonageDisplayer {}
}

package game{
                class Apocalypse {}
                interface Board {}
                interface Game {}
                class ApocalypseCreator {}
                interface GameCreator {}
                class GameState {}
                class Position {}
                class RandomPositionGenerator {}
                class SimpleBoard {}
                class Tile {}
                class TileResult {}
}

package move{
                class Move {}
                class RandomMoveGenerator {}
}


@enduml