@startuml
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml


start
:Put the infected on the map;

-[#black]->
partition "Each turn" {
if (Is infected alive) then (yes)
    -[#black]->
:Move infected randomly;
-[#black]->
if (Is opponent on the same tile) then (yes)
  -[#black]->
  :Attack him;
  -[#black]->
  :Increase attack damage;

  -[#black]->
else (no)
    -[#black]->
endif
    -[#black]->
    else (no)
    -[#black]->
endif
}
-[#black]->


stop
@enduml